Improve docs for events inputs
nektos/act pull request #1238
Opened 2022-07-01 00:46 UTC by mhnaeem

Added documentation on how to pass inputs for workflows that require them in the README file to have better visibility.

2022-07-01 04:50 UTC, KnisterPeter requested changes
This need some updates

2022-07-01 04:50 UTC, KnisterPeter commented on README.md
> +  "action": "workflow_dispatch",
The action isn't the event name. You will have to pass 'workflow_dispatch' as cli parameter, otherwise act will run a push event

2022-07-01 04:50 UTC, KnisterPeter commented on README.md
> +act -e payload.json
Add 'workflow_dispatch' here

2022-07-01 06:19 UTC, mhnaeem commented on README.md
> +act -e payload.json
Done, thanks I almost missed that!

2022-07-04 07:20 UTC, KnisterPeter approved these changes

2022-07-05 19:05 UTC, merged