fix: tolerate workflow that needs a missing job (#1595)
nektos/act pull request #1619
Opened 2023-02-08 16:55 UTC by jsoref

Fixes #1595

2023-02-09 03:20 UTC, jsoref commented
With this, I'm able to run `act -l` for the vector repository and get something reasonable

<details><summary>output</summary>

```
jsoref@jsoref-mbp vector % ../nektos/act/dist/local/act -l
WARN  ⚠ You are using Apple M1 chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
WARN[0000] unable to build dependency graph for Test Harness (test-harness.yml)
Stage  Job ID                                         Job name                                                                                                                Workflow name                  Workflow file            Events
0      release-build-normal                           Release Build (normal)                                                                                                  Baseline Timings               baseline.yml             workflow_dispatch,schedule
0      debug-build                                    Debug Build                                                                                                             Baseline Timings               baseline.yml             workflow_dispatch,schedule
0      debug-rebuild                                  Debug Rebuild                                                                                                           Baseline Timings               baseline.yml             schedule,workflow_dispatch
0      check                                          Cargo Check                                                                                                             Baseline Timings               baseline.yml             workflow_dispatch,schedule
0      release-build-optimized                        Release Build (optimized)                                                                                               Baseline Timings               baseline.yml             workflow_dispatch,schedule
0      publish-new-environment                        publish-new-environment                                                                                                 Environment Suite              environment.yml          pull_request,push,workflow_dispatch
0      add-to-project                                 Add issue to Gardener project board                                                                                     gardener_open_issue.yml        gardener_open_issue.yml  issues
0      add-dependabot-to-project                      Add dependabot PR to Gardener project board                                                                             gardener_open_pr.yml           gardener_open_pr.yml     pull_request_target
0      add-contributor-to-project                     Add contributor PR to Gardener project board                                                                            gardener_open_pr.yml           gardener_open_pr.yml     pull_request_target
0      sync-install                                   sync-install                                                                                                            Update install.sh Suite        install-sh.yml           push,workflow_dispatch
0      test-integration                               Integration - Linux, ${{ matrix.test }}                                                                                 Integration Test Suite         integration-test.yml     workflow_dispatch,push,pull_request
0      build-x86_64-unknown-linux-gnu                 Build - x86_64-unknown-linux-gnu                                                                                        K8S E2E Suite                  k8s_e2e.yml              workflow_dispatch,push,pull_request
0      compute-k8s-test-plan                          Compute K8s test plan                                                                                                   K8S E2E Suite                  k8s_e2e.yml              workflow_dispatch,push,pull_request
0      label                                          label                                                                                                                   Pull Request Labeler           labeler.yml              pull_request_target
0      Nightly                                        Nightly                                                                                                                 Nightly                        nightly.yml              workflow_dispatch,schedule
0      generate-publish-metadata                      Generate Publish-related Metadata                                                                                       Publish                        publish.yml              workflow_call
0      cancel-previous                                cancel-previous                                                                                                         Regression Detector            regression.yml           pull_request
0      compute-metadata                               Compute metadata for regression experiments                                                                             Regression Detector            regression.yml           pull_request
0      compute-metadata                               Compute metadata for regression experiments                                                                             Regression Detector (trusted)  regression_trusted.yml   workflow_run
0      Release                                        Release                                                                                                                 Release Suite                  release.yml              push
0      spelling                                       Check Spelling                                                                                                          Check Spelling                 spelling.yml             push,pull_request_target
0      changes                                        changes                                                                                                                 Test Suite                     test.yml                 pull_request,push
1      test-install                                   test-install                                                                                                            Update install.sh Suite        install-sh.yml           push,workflow_dispatch
1      test-integration-check                         test-integration-check                                                                                                  Integration Test Suite         integration-test.yml     push,pull_request,workflow_dispatch
1      test-e2e-kubernetes                            K8s ${{ matrix.kubernetes_version.version }} / ${{ matrix.container_runtime }} (${{ matrix.kubernetes_version.role }})  K8S E2E Suite                  k8s_e2e.yml              push,pull_request,workflow_dispatch
1      build-x86_64-pc-windows-msvc-packages          Build Vector for x86_64-pc-windows-msvc (.zip)                                                                          Publish                        publish.yml              workflow_call
1      build-armv7-unknown-linux-gnueabihf-packages   Build Vector for armv7-unknown-linux-gnueabihf (.tar.gz)                                                                Publish                        publish.yml              workflow_call
1      build-aarch64-unknown-linux-gnu-packages       Build Vector for aarch64-unknown-linux-gnu (.tar.gz)                                                                    Publish                        publish.yml              workflow_call
1      build-x86_64-unknown-linux-musl-packages       Build Vector for x86_64-unknown-linux-musl (.tar.gz)                                                                    Publish                        publish.yml [...]

2023-02-13 15:24 UTC, KnisterPeter requested changes
Looks fine, just the debug output seems to be wrong

2023-02-13 15:24 UTC, KnisterPeter commented on pkg/model/planner.go
> +		log.Debugf("no workflows found for workflow: %s", eventName)
This should probably be

```suggestion
		log.Debugf("no workflows found for event: %s", eventName)
```

2023-02-14 07:56 UTC, KnisterPeter reviewed
I'm fine with this now, but @ChristopherHX has a valid point.
If that's fixed I'll approve

2023-02-14 14:24 UTC, jsoref commented
I'm happy to apply most of that. This seems unnecessary:

```
-		log.Debug("no workflows found by planner")
+		log.Debugf("no workflows found by planner")
```

2023-02-14 14:31 UTC, jsoref commented
(I'm just trying to convince my computer to run some tests in VSCode before I amend.)

2023-02-16 15:15 UTC, KnisterPeter approved these changes

2023-02-16 16:41 UTC, merged