fix: accept platforms name contained equal sigh
nektos/act pull request #2160
Opened 2024-01-19 20:59 UTC by totechite

Fix #2159
I hope to help ACT user using GitHub EnterPrise Server.

2024-01-24 02:21 UTC, wolfogre requested changes
I have read #2159 carefully, however, I didn't see a strong reason to support `=` in the platform name. Could you please explain why it will help users using GitHub Enterprise Server? Why is `=` required? TBH, I think `IMAGE=debian-12=nektos/act-environments-ubuntu:22.04` is quite confusing.

2024-01-25 04:29 UTC, totechite commented
@wolfogre 
Thank you for checking 
As you may know, GHE users can't pick the GH Managed runner service so, we necessarily use self-hosted-runner when using GH Actions.

In my case, I use self-hosted-runners that are labeled the name `IMAGE=debian-12` at my organization. 
however, I can't use act in my workspace using GHE because of this issue. And I don't hope to modify the runner-label for using this tool.

runner-label 's specification  accepts `=` so if act support self-hosted-runner platform, may need this change. 

thanks.

2024-01-26 07:11 UTC, wolfogre commented
Sorry, I'm afraid I need to reserve my opinion. I don't see a strong reason to include `=` in the label name in your case.

For most command tools, `a=b=c` will be treated as `a: b=c`, like `docker run --env a=b=c --label a=b=c`. And act has many parameters with key-value format. I hope they could keep the same behavior to avoid confusion.

```bash
$ act -h | grep stringArray
      --container-cap-add stringArray                     kernel capabilities to add to the workflow containers (e.g. --container-cap-add SYS_PTRACE)
      --container-cap-drop stringArray                    kernel capabilities to remove from the workflow containers (e.g. --container-cap-drop SYS_PTRACE)
      --env stringArray                                   env to make available to actions with optional value (e.g. --env myenv=foo or --env myenv)
      --input stringArray                                 action input to make available to actions (e.g. --input myinput=foo)
      --matrix stringArray                                specify which matrix configuration to include (e.g. --matrix java:13
  -P, --platform stringArray                              custom image to use per platform (e.g. -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04)
      --replace-ghe-action-with-github-com stringArray    If you are using GitHub Enterprise Server and allow specified actions from GitHub (github.com), you can set actions on this. (e.g. --replace-ghe-action-with-github-com =github/super-linter)
  -s, --secret stringArray                                secret to make available to actions with optional value (e.g. -s mysecret=foo or -s mysecret)
      --var stringArray                                   variable to make available to actions with optional value (e.g. --var myvar=foo or --var myvar)
```

2024-01-27 05:33 UTC, totechite commented
I agree with your thoughts, but how should I interpret the message here, which is also mentioned in #2159 ? 
It seems to accept `a=b: c`.
> [test workflow/demo] 🚧 Skipping unsupported platform -- Try running with `-P IMAGE=debian-12=...

I would like to avoid changing the runner-label name to use act if possible.
This is a so useful tool, but when using GH Actions, I don't hope should not be forced to use label names that take into account the specifications of this tool .

2024-01-27 05:38 UTC, totechite commented
How about modifying the content to accept the format of grouping the key string with any symbols. Would it look ugly?  `'a=b'=c`

2024-01-31 18:25 UTC, totechite commented
@wolfogre Please re-review.

2024-02-03 03:12 UTC, allexiusw reviewed
Can we have some unittests for this feature?

2024-02-03 03:12 UTC, allexiusw commented on cmd/platforms.go
> +		platforms[strings.ToLower(pName)] = pValue
Wondering if we can have tests for this? Not sure if there is a rule where you should add tests for each new feature.

2024-02-18 03:59 UTC, wolfogre commented
> @wolfogre Please re-review.

I take a neutral stance on this. Please ignore my change request and let other maintainers decide.

2024-08-31 00:11 UTC, closed without merging