envs in if: - take 2
nektos/act pull request #412
Opened 2020-11-09 20:29 UTC by torbjornvatn

I discovered that table based tests must have define `assert := a.New(t)` inside the `t.Run` internal func. 
If not, the assert wasn't actually asserting correctly 🙈 

This lead to the discovery of some test cases that wasn't actually working. 
I had to make several changes to the EvalBool function support all the permutations of negations, envs and interpolations

2020-11-10 22:58 UTC, cplee requested changes
looks great! one change requested...

2020-11-10 22:58 UTC, cplee commented on pkg/runner/expression.go
> +	"github.com/opencontainers/runc/Godeps/_workspace/src/github.com/Sirupsen/logrus"
can this be removed?

2020-11-12 08:27 UTC, torbjornvatn commented
@cplee the stray logrus import is removed now.

2020-11-12 16:14 UTC, cplee approved these changes

2020-11-12 16:15 UTC, merged