Fixes Issue #597
nektos/act pull request #637
Opened 2021-04-25 14:35 UTC by Renstrom

Fixes #597 

Due to the order of events, the stepenv was evaluated before the if statement was checked. This fix changes the order of events aswell as tests to test this. Inspiration of the test was taken from #597. 

As I understand the code, I think this solution fixes it.

2021-04-26 15:09 UTC, catthehacker requested changes

2021-04-26 15:43 UTC, Renstrom commented on pkg/runner/runner_test.go
> +		{"testdata", "issue597", "push", "", platforms, "linux/arm64"},
@catthehacker Done

2021-05-03 14:56 UTC, cplee commented
@Renstrom - 1 conflict and ready to merge 🚀

2021-05-03 15:07 UTC, Renstrom commented
@cplee  Fixed

2021-05-03 16:51 UTC, cplee approved these changes

2021-05-03 16:51 UTC, merged