Improve typography
nektos/act pull request #745
Opened 2021-06-26 12:28 UTC by wmyfelix

2021-06-26 12:42 UTC, catthehacker requested changes

2021-06-26 12:42 UTC, catthehacker commented on README.md
> +## macOS
Homebrew can be used on Linux as well.

2021-06-26 12:42 UTC, catthehacker commented on README.md
> +## Linux
homebrew.

2021-06-28 11:26 UTC, wmyfelix commented
I'll finish the CN translations before August

2021-07-18 04:17 UTC, wmyfelix commented
I have time to translate now, but I don’t know if it’s necessary for `act`

2021-07-28 07:03 UTC, closed without merging