Fixes
nektos/act pull request #856
Opened 2021-11-02 05:00 UTC by jsoref

I was getting output like this:
```
[choco/choco] Filesystem      Size  Used Avail Use%!M(MISSING)ounted on
overlay          59G  9.0G   47G  17%!/(MISSING)
tmpfs            64M     0   64M   0%!/(MISSING)dev
tmpfs           993M     0  993M   0%!/(MISSING)sys/fs/cgroup
shm              64M     0   64M   0%!/(MISSING)dev/shm
/dev/vda1        59G  9.0G   47G  17%!/(MISSING)etc/hosts
tmpfs           993M     0  993M   0%!/(MISSING)proc/acpi
tmpfs           993M     0  993M   0%!/(MISSING)sys/firmware
```
Which was very confusing.

Also output like this:
```
[choco/choco]  🐳  docker build -t act-github-actions-choco-dockeraction:latest --platform  /Users/jsoref/code/nektos/act/.github/actions/choco
[choco/choco] RBuilding image from '/Users/jsoref/code/nektos/act/.github/actions/choco'
[choco/choco] RCreating image from context dir '/Users/jsoref/code/nektos/act/.github/actions/choco' with tag 'act-github-actions-choco-dockeraction:latest' and platform ''
```

I also tripped over an error involving not enough disk space. There's no reason to install `wget`, `tar`, or `gzip` on a normal image as `curl` can download things and the busybox tar can handle its output.

2021-11-02 08:47 UTC, catthehacker requested changes

2021-11-02 08:47 UTC, catthehacker commented on .github/actions/choco/Dockerfile
>  RUN mv "choco-${CHOCOVERSION}" choco
`wget`, `tar` and `gzip` are not that big and provide different behaviour to `busybox`, I would like to leave it like that since it works

2021-11-02 08:53 UTC, catthehacker approved these changes

2021-11-02 09:03 UTC, jsoref commented
> Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

😕

2021-11-03 18:46 UTC, cplee approved these changes

2021-11-03 18:47 UTC, merged