feat: try to read ref and sha from event payload if available
nektos/act pull request #889
Opened 2021-11-17 19:52 UTC by ZauberNerd

With this change `act` will try to populate the `githubContext.ref` and
`githubContext.sha` with values read from the event payload.

Caveats:
- `page_build` should not have a ref
- `status` should not have a ref
- `registry_package` should set the ref to the branch/tag but the
  payload isn't documented
- `workflow_call` should set ref to the same value as its caller but the
  payload isn't documented
- most of the events should set the sha to the last commit on the ref
  but unfortunately the sha is not always included in the payload,
  therefore we use the sha from the local git checkout

2021-12-04 19:19 UTC, catthehacker commented
Could you add some test cases?

2022-01-03 19:37 UTC, catthehacker approved these changes

2022-01-03 19:38 UTC, catthehacker requested changes
Still missing test cases

2022-01-04 13:15 UTC, ZauberNerd commented
@catthehacker I added some tests, can you please take another look?

2022-01-04 18:06 UTC, KnisterPeter approved these changes

2022-01-06 16:38 UTC, catthehacker approved these changes
Looks more than "some" 😄 thanks a lot

2022-01-21 16:09 UTC, cplee approved these changes

2022-01-21 16:10 UTC, merged